### ISSUE TITLE
Error on inserting not displayed

### ISSUE THREAD

**Issue by bfeaver** [derptest/phpmachinist#57]
When inserting a blueprint row into a table that has columns that cannot be null, the insert silently fails. An error should be produced so that the user doesn't need to dig through machinist code to figure out why data isn't being inserted.

**Comment by aenglander** [comment]
It's probably a good idea that this be added.  Until that time there is a work around that you can use by setting the error mode like so:

```php
$pdo->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

```

The default mode is silent and requires checking the error info.  Setting the error mode to exception will fail the test for the database error.
